### ISSUE TITLE
Puppeteer needs to be updated if you want this to be adopted by big organizations

### ISSUE THREAD

**Issue by Vasanthagokul** [Garethp/aws-azure-auth#4]
Recently, bigger organizations have started to block chromium v101 which is found in puppeteer 13.7 bcuz it uses chromium v101 which is extremely out of date. A simple update to the version and the corresponding usage might help you make this project bigger. update puppeteer to v22 and I think you'll be good for a good 5 years.

**Comment by Garethp** [comment]
Sounds good, I'll try to get that in in the next couple of days

**Comment by cjnoname** [comment]
Hi @Garethp, how is it going?

**Comment by Garethp** [comment]
Thanks for your patience @Vasanthagokul and @cjnoname. I ended up having to dedicate more time than planned to other projects, but I've released version 1.0.1 of `aws-azure-auth`, which uses the latest major version of Puppeteer. I've made a very small start on unit testing aws-azure-auth, and when it's in a state with a good amount of unit tests I'll look at running Renovate or another dependency management tool to keep dependencies like Puppeteer up to date while still keeping them as pinned dependency versions.

Please pull down `1.0.1` and let me know if you run into any issues with it
